### ISSUE TITLE
トークリストにブックマーク済みのマークが欲しい

### ISSUE THREAD

**Issue by mass10** [pyconjp/pyconjp-ios#50]
「カンファレンス」でトークリストを見たときに、「どのトークをブックマークしているか」がわかるとよさそうではないかと思いました！

**Comment by yutailang0119** [comment]
@mass10 データ更新通知の部分の実装が、現状の作りだとうまくいかず、他のリリースに影響を与えているので、マイルストーンから外しました。

**Comment by yutailang0119** [comment]
Timetable対応ついでに対応done
